spring:
  application:
    name: mygallery
  profiles:
    default: memory

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
