spring:
  datasource:
    url: ${MYGALLERY_DB_URL}
    username: ${MYGALLERY_DB_USERNAME}
    password: ${MYGALLERY_DB_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
